name: Zailyn's Website
description: My Website
url: http://zailyn-tamayo.com

exclude:
  - deprecated
  - vendor
  - Gemfile
  - Gemfile.lock
  - Procfile

safe: true

highlighter: rouge

markdown: kramdown

gems:
  - jekyll-redirect-from

markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"